### ISSUE TITLE
Github actions not running due to failing tests

### ISSUE THREAD

**Issue by Achoobert** [digi-serve/ab_service_api_sails#100]
These are inconsistent, and different sets of failed tests show up on new runs of the action

The tests before merging a Pull request seem to work perfectly. The issue seems to be specific to the image builder

```
  3 failing

  1) Widget Tests
       DOCX Builder
         Downloading:
     AssertionError: Timed out retrying after 40000ms: Expected to find element: `[data-cy^="docx download DOCX Builder"] > .fa-file-word-o`, but never found it.
      at Context.eval (webpack:///./cypress/e2e/kitchensink_app/test_cases/widget_docx_builder.js:14:13)

  2) Widget Tests
       FilterByConnectedRecord
         Filtering ByDefault:
     AssertionError: Timed out retrying after 40000ms: Expected to find element: `[data-cy^="connectObject connectto3"]`, but never found it.
      at Context.eval (webpack:///./cypress/e2e/kitchensink_app/test_cases/widget_filter_by_connected_record.js:25:13)

  3) Widget Tests
       Save Form Values
         Submit Empty Number Field:
     CypressError: Timed out retrying after 40050ms: `cy.click()` failed because this element:

`<div class="edit">...</div>`

is being covered by another element:

`<div class="webix_progress_icon" role="progressbar" aria-valuemin="0" aria-valuemax="100" tabindex="0">...</div>`

Fix this problem, or use {force: true} to disable error checking.
  71 passing (8m)
  3 pending
  1 failing

  1) Widget Tests
       Does combo index work
         new records work?:
     AssertionError: Timed out retrying after 40000ms: Expected <div.webix_progress_state.wxi-sync.webix_spin> not to exist in the DOM, but it was continuously found.
      at Context.eval (webpack:///./cypress/e2e/kitchensink_app/test_cases/widget_combo.js:40:31)



  70 passing (15m)
  3 pending
  2 failing

  1) Widget Tests
       Text
         Exists:

      Timed out retrying after 40000ms
      + expected - actual

      +'longtext'
      
      at Context.eval (webpack:///./cypress/e2e/kitchensink_app/test_cases/widget_text.js:11:13)

  2) Process Tests
       Process Approval
         Can see the message for approval in the inbox:

      AssertionError: Timed out retrying after 40000ms: Too many elements found. Found '8', expected '7'.
      + expected - actual

      -8
      +7
      
      at Context.eval (webpack:///./cypress/e2e/kitchensink_app/test_cases/process_approval.js:41:13)
//////
  1) Widget Tests
       Detail
         Exists:

      Timed out retrying after 40000ms
      + expected - actual

      -'test-kcs-id'
      +'Test-KCS-'
      
      at Context.eval (webpack:///./cypress/e2e/kitchensink_app/test_cases/widget_detail.js:12:13)

  2) Widget Tests
       DOCX Builder
         Downloading:
     AssertionError: Timed out retrying after 40000ms: Expected to find element: `[data-cy^="docx download DOCX Builder"] > .fa-file-word-o`, but never found it.
      at Context.eval (webpack:///./cypress/e2e/kitchensink_app/test_cases/widget_docx_builder.js:14:13)

  3) Widget Tests
       Save Form Values
         Submit Record Rules Form:
     CypressError: Timed out retrying after 40050ms: `cy.click()` failed because this element:

`<div class="trash">...</div>`

is being covered by another element:

`<div class="webix_progress_icon" role="progressbar" aria-valuemin="0" aria-valuemax="100" tabindex="0">...</div>`
  4) Widget Tests
       Save Form Values
         Submit Default Values Form:
     CypressError: Timed out retrying after 40050ms: `cy.click()` failed because this element:

`<div class="trash">...</div>`

is being covered by another element:

`<div class="webix_progress_icon" role="progressbar" aria-valuemin="0" aria-valuemax="100" tabindex="0">...</div>`

  5) Widget Tests
       Save Form Values
         Submit Empty Number Field:
     AssertionError: Timed out retrying after 40000ms: Expected to find element: `.edit`, but never found it.
      at Context.eval (webpack:///./cypress/e2e/kitchensink_app/test_cases/widget_form_save.js:65:25)


  1) Widget Tests
       Carousel
         Check fa arrows:
     AssertionError: Timed out retrying after 40000ms: Expected to find element: `span`, but never found it. Queried from:

              > cy.get([data-cy="carousel 54827db6-497b-43ae-96f9-153b63a9c977"])
      at Context.eval (webpack:///./cypress/e2e/kitchensink_app/test_cases/widget_carousel.js:24:13)

  2) Widget Tests
       Text
         Exists:

      Timed out retrying after 40000ms
      + expected - actual

      +'longtext'
      
      at Context.eval (webpack:///./cypress/e2e/kitchensink_app/test_cases/widget_text.js:11:13)

  3) Process Tests
       Process Approval
         Can see the message for approval in the inbox:

      AssertionError: Timed out retrying after 40000ms: Too many elements found. Found '8', expected '7'.
      + expected - actual

      -8
      +7
      
      at Context.eval (webpack:///./cypress/e2e/kitchensink_app/test_cases/process_approval.js:41:13)

```

**Comment by Achoobert** [comment]
```
  1) Widget Tests
       FilterByConnectedRecord
         Filtering ByCustomIndex:
     AssertionError: Timed out retrying after 40000ms: Expected to find element: `[data-cy^="connectObject connectto3"]`, but never found it.
      at Context.eval (webpack:///./cypress/e2e/kitchensink_app/test_cases/widget_filter_by_connected_record.js:79:12)

  2) Widget Tests
       Grid
         Can edit connected records:
     AssertionError: Timed out retrying after 40000ms: Expected to find element: `.webix_column[column="27"] > [role="gridcell"][aria-rowindex="1"]`, but never found it.
      at Context.eval (webpack:///./cypress/e2e/kitchensink_app/test_cases/widget_grid.js:44:19)
```

**Comment by Achoobert** [comment]
Adding a retry, and adjusting the tests seems to have helped
